name: Deploy to EC2

on:
  push:
    branches: [ master ]   # change if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY  }}
          script: |
            cd /home/ec2-user/springBoot

            echo "Pulling latest code..."
            git pull origin master

            echo "Building project..."
            cd ticket-booking-lambda
            mvn clean package -DskipTests

            echo "Stopping old app (if running)..."
            pkill -f 'ticket-booking-lambda-0.0.1-SNAPSHOT.jar' || false

            echo "Starting new app..."
            nohup java -jar target/ticket-booking-lambda-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            echo "Deployment finished."
